baseURL = "https://silverstrike.org/"
languageCode = "en-us"
title = "SilverStrike"
theme = "editorial"

[params]
    name = "Simon Hanna"
    description = "description"
    dateFormat = "02.01.2006"
    title = "SilverStrike"
    learnmore = "Learn More"
    learnmorelink = "overview"
    [params.sidebar]
        bio = "**SilverStrike**<br> a simple finance<br> management webapp"
        title = "Menu"
        copyright = "&copy; Simon Hanna<br>Project License: MIT<br>Website License: CC-BY-4.0<br>Design: [HTML5 UP](//html5up.net)"
    [params.contact]
        hide = true
        title = "Get In Touch"
        email = "dev@silverstrike.org"
    [params.portfolio]
        hide = true
    [params.recentposts]
        hide = true


[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    weight = 2

[[menu.main]]
    name = "Setup"
    weight = 3

[[menu.main]]
    name = "Demo"
    weight = 5
    url = "https://demo.silverstrike.org"

[[menu.main]]
    name = "Contributing"
    weight = 4

