baseURL = "https://agstrike.github.io/"
languageCode = "en-us"
title = "SilverStrike"
theme = "editorial"

[params]
    name = "Simon Hanna"
    description = "description"
    dateFormat = "02.01.2006"
    title = "SilverStrike"
    learnmore = "Learn More"
    learnmorelink = "overview"
    [params.sidebar]
        bio = "**SilverStrike**<br> a simple finance<br> management webapp"
        title = "Menu"
        copyright = """&copy; Simon Hanna  
        Project License: MIT  
        Website License: CC-BY-4.0  
        Design: [HTML5 UP](//html5up.net)"""
    [params.portfolio]
        hide = true
    [params.recentposts]
        hide = true


[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    weight = 2

[[menu.main]]
    name = "Setup"
    weight = 3

